# Generated by Django 4.2.15 on 2024-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicGatewayCache",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=2048, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=2048)),
                ("identifier", models.CharField(max_length=2048)),
                ("publisher", models.CharField(max_length=2048)),
                ("language", models.CharField(max_length=2048)),
                ("format", models.CharField(max_length=2048)),
                ("description", models.TextField()),
                ("date_issued", models.CharField(max_length=2048)),
                ("date_modified", models.DateTimeField()),
                ("date_valid", models.DateTimeField()),
                ("audience", models.CharField(max_length=2048)),
                ("coverage", models.CharField(max_length=2048)),
                ("subject", models.CharField(max_length=2048)),
                ("type", models.CharField(max_length=2048)),
                ("license", models.CharField(max_length=2048)),
                ("regulatory_topics", models.CharField(max_length=2048)),
                ("status", models.CharField(max_length=2048)),
                ("date_uploaded_to_orp", models.CharField(max_length=2048)),
                ("has_format", models.CharField(max_length=2048)),
                ("is_format_of", models.CharField(max_length=2048)),
                ("has_version", models.CharField(max_length=2048)),
                ("is_version_of", models.CharField(max_length=2048)),
                ("references", models.CharField(max_length=2048)),
                ("is_referenced_by", models.CharField(max_length=2048)),
                ("has_part", models.CharField(max_length=2048)),
                ("is_part_of", models.CharField(max_length=2048)),
                ("is_replaced_by", models.CharField(max_length=2048)),
                ("replaces", models.CharField(max_length=2048)),
                ("related_legislation", models.CharField(max_length=2048)),
                ("search_terms", models.CharField(max_length=2048)),
                ("document_types", models.CharField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
