# Generated by Django 4.2.16 on 2024-11-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orp_search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataresponsemodel",
            old_name="search_terms",
            new_name="query",
        ),
    ]
